spring.application.name=service
server.port=8081

# oauth server
##    - vends && validates tokens

# oauth client
##   - user facing app w/ user context

# resource server
##   - backend api with no user facing client

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090
